### PR TITLE
Add missing php dependencies for nginx image

### PR DESCRIPTION
**Pull request by languitar**
Without these dependencies, baikal cannot be used.

### CODE REVIEW

**Comment by ckulka** [comment]
Hi  @languitar , thanks for the PR - when do you get the error messages that these dependencies are missing? I went through my logs, but couldn't find anything.

Also, could you please also sort the dependencies in alphabetical order and add them to the other Dockerfiles as well?

**Comment by languitar** [comment]
Sorry for the delay. I have added the dependencies also to the arm nginx image. I am not sure about the apache versions, because I don't use them an I am not sure what is already included there.

I have migrated an existing installation of baikal to the docker image and without these dependencies, first launch failed immediately. I don't have the logs available anymore, though. :/

**Comment by languitar** [comment]
Maybe @dober knows more about what fails without those dependencies?

**Comment by dober** [comment]
Sure!
Without this deps we got an error:

https://davserver/card.php/addressbooks/user/contacts

`Error: Class 'DOMDocument' not found in /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php:256
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php(123): Sabre\DAV\Server->exec()
#1 /var/www/baikal/html/card.php(62): Baikal\Core\Server->start()
#2 {main}`

**Comment by mehdicopter** [comment]
Hello,
Please @ckulka add this PR.
[(https://github.com/sabre-io/Baikal/wiki/Ba%C3%AFkal-dependencies)]

**Pull request merged**
