### PR TITLE
Baikal: add Unraid installation guide

### PR DESCRIPTION
**Pull request by Joshndroid**
Add an Unraid installation guide I had developed while working on getting this installed on my own Unraid server.
Note within guide the creation of an Unraid template (available directly within unraid) for users if they were curious regarding an easier installation method.
Note also within guide the template is only a template and utilises the same docker as developed here.
Provide guide for manual installation purposes or learning purposes for others on unraid

Signed-off-by: Joshndroid <fmxjoshiewah@gmail.com>

### CODE REVIEW

**Comment by ckulka** [comment]
Thanks!

I made a few adjustments to add links to further documentation and other smaller things - before I merge it, can you please have another look to make sure I didn't introduce typos or (worse) incorrect statements?

**Comment by Joshndroid** [comment]
From what i have read it seems fine.
While this guide can be used I have also added the ability in unraid to use a template which is how the unraid community apps section works. It tracks this docker container and changes, etc as you update the docker. It just simplifies the setup to which a lot of these entries are already preconfigured rather than the manual method outlined here. This guide is definitely valid and can be used as a reference for others out there or to assist in the settings that are required even when using the docker template method within unraid.

**Comment by ckulka** [comment]
What's the link to the template? I can then add it to the guide.

**Comment by Joshndroid** [comment]
Currently it's accessible by clicking on apps and searching for baikal either by name or through 'new apps' or through 'network:web'.. At present the community apps actual website does not appear to be up to date but the local repo with unraid does show it.

**Comment by Joshndroid** [comment]
That's how it shows in the community apps section as of now (sorry I'm on mobile)

**Pull request merged**
