### PR TITLE
add example with custom storage location instead of /var/lib/docker/.../

### PR DESCRIPTION
**Pull request by funkythings**

### CODE REVIEW

**Comment by ckulka** [comment]
Hi Julian, thanks!

I'll run a quick test and merge it when I'm back home, I'm just stuck in
the Dominican Republic at the moment.

Best regards,
Cyrill

**Comment by funkythings** [comment]
No worries! World's crazy right now...

Thanks for the great docker image! Been running very smoothely this past week

**Comment by ckulka** [comment]
Thanks @funkythings !

**Comment by funkythings** [comment]
No problem.

**Pull request merged**
